directories:
  output: ./pkg/
  buildResources: build
appId: com.ivanalejandro0.when-are-you
files:
  - filter:
      - ./dist/**/*
      - ./clock.png
      - package.json
      - ./dist-ui/**/*
mac:
  category: your.app.category.type
electronVersion: 11.0.1
