directories:
  output: ./pkg/
  buildResources: build
appId: com.ivanalejandro0.when-are-you
extraMetadata:
  name: when-are-you
files:
  - filter:
      - ./dist/**/*
      - ./dist-ui/**/*
      - ./clock.png
      - package.json
mac:
  category: your.app.category.type
  target:
    target: dmg
    arch:
      - x64
      - arm64
linux:
  target: appimage
electronVersion: 19.0.1
