name: build-and-release

# Controls when the action will run.
on:
  # Triggers the workflow on push event but only for tags
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true

  build:
    needs: create_release
    strategy:
      matrix:
        build: [linux, mac]
        include:
        - build: linux
          os: ubuntu-latest
        - build: mac
          os: macos-latest

    # The type of runner that the job will run on
    runs-on: ${{matrix.os}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      # Runs a set of commands using the runners shell
      - name: Package app
        run: |
          yarn
          yarn package

      - name: "Upload build: Linux"
        if: matrix.build == 'linux'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # This pulls from the CREATE RELEASE step above, referencing it's ID
          # to get its outputs object, which include a `upload_url`. See this
          # blog post for more info:
          # https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./electron/pkg/when-are-you-0.0.0.AppImage
          asset_name: when-are-you-${{ github.ref }}.tar.xz
          asset_content_type: application/x-xz-compressed-tar

      - name: "Upload build: Mac x64"
        if: matrix.build == 'mac'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./electron/pkg/when-are-you-0.0.0.dmg
          asset_name: when-are-you-${{ github.ref }}.dmg
          asset_content_type: application/x-apple-diskimage

      - name: "Upload build: Mac arm64"
        if: matrix.build == 'mac'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./electron/pkg/when-are-you-0.0.0-arm64.dmg
          asset_name: when-are-you-${{ github.ref }}-arm64.dmg
          asset_content_type: application/x-apple-diskimage
